# Generated by Django 5.1.1 on 2024-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('middleInitial', models.CharField(blank=True, max_length=10, verbose_name='MI')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='Suffix')),
                ('sex', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, verbose_name='Sex')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('contactNumber', models.CharField(blank=True, max_length=20, verbose_name='Contact Number')),
                ('authorityDate', models.DateField(blank=True, null=True, verbose_name='Authority Date')),
                ('mtf', models.CharField(blank=True, choices=[('AFGH', 'AFGH'), ('FABH', 'FABH'), ('AFCH', 'AFCH'), ('CGARSH', 'CGARSH'), ('BGBNEABH', 'BGBNEABH'), ('EAABH', 'EAABH')], max_length=10, verbose_name='MTF')),
                ('purpose', models.CharField(blank=True, choices=[('SE', 'SE'), ('CS', 'CS')], max_length=10, verbose_name='Purpose')),
                ('labDateStarted', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('labDateCompleted', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('labStatus', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('w/ COMPLIANCE', 'w/ COMPLIANCE'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='LAB Status')),
                ('labRemarks', models.TextField(blank=True, max_length=250, verbose_name='LAB Remarks')),
                ('ecgDateStarted', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('ecgDateCompleted', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('ecgStatus', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('w/ COMPLIANCE', 'w/ COMPLIANCE'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='ECG Status')),
                ('ecgRemarks', models.TextField(blank=True, max_length=250, verbose_name='ECG Remarks')),
                ('xrayDateStarted', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('xrayDateCompleted', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('xrayStatus', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('w/ COMPLIANCE', 'w/ COMPLIANCE'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='X-ray Status')),
                ('xrayRemarks', models.TextField(blank=True, max_length=250, verbose_name='X-ray Remarks')),
                ('npDateStarted', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('npWrittenExam', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='NP Written Exam')),
                ('npInitialInterview', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='NP Written Exam')),
                ('npFinalInterview', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='NP Written Exam')),
                ('npDateCompleted', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('npStatus', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('w/ COMPLIANCE', 'w/ COMPLIANCE'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='NP Status')),
                ('npRemarks', models.TextField(blank=True, max_length=250, verbose_name='NP Remarks')),
                ('dentalDateStarted', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('dentalDateCompleted', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('dentalStatus', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('w/ COMPLIANCE', 'w/ COMPLIANCE'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='Dental Status')),
                ('dentalRemarks', models.TextField(blank=True, max_length=250, verbose_name='Dental Remarks')),
                ('immunizationDateStarted', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('immunizationDateCompleted', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('immunizationStatus', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('w/ COMPLIANCE', 'w/ COMPLIANCE'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='Immunization Status')),
                ('immunizationRemarks', models.TextField(blank=True, max_length=250, verbose_name='Immunization Remarks')),
                ('drugTestDateStarted', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('drugTestDateCompleted', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('drugTestStatus', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('w/ COMPLIANCE', 'w/ COMPLIANCE'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='Drug Test Status')),
                ('drugTestRemarks', models.TextField(blank=True, max_length=250, verbose_name='Drug Test Remarks')),
                ('eentTestDateStarted', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('eentTestDateCompleted', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('eentTestStatus', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('w/ COMPLIANCE', 'w/ COMPLIANCE'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='EENT Test Status')),
                ('eentTestRemarks', models.TextField(blank=True, max_length=250, verbose_name='EENT Test Remarks')),
                ('genPhyTestDateStarted', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('genPhyTestDateCompleted', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('genPhyTestStatus', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('w/ COMPLIANCE', 'w/ COMPLIANCE'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='GenPhy Test Status')),
                ('genPhyTestRemarks', models.TextField(blank=True, max_length=250, verbose_name='GenPhy  Test Remarks')),
                ('ocsafStatus', models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('ONGOING', 'ONGOING'), ('DNR', 'DNR'), ('DNC', 'DNC'), ('DQ', 'DQ')], max_length=50, verbose_name='OCSAF Status')),
                ('ocsafFindings', models.TextField(blank=True, max_length=250, verbose_name='OCSAF Findings')),
                ('ocsafDateOfCert', models.DateField(blank=True, null=True, verbose_name='OCSAF Date of Certification')),
                ('ocsafRemarks', models.TextField(blank=True, max_length=250, verbose_name='OCSAF Remarks')),
            ],
        ),
    ]
