# Generated by Django 5.1.1 on 2024-09-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='eentTestDateCompleted',
            new_name='eentDateCompleted',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='eentTestDateStarted',
            new_name='eentDateStarted',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='eentTestRemarks',
            new_name='eentRemarks',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='eentTestStatus',
            new_name='eentStatus',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='genPhyTestDateCompleted',
            new_name='genPhyDateCompleted',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='genPhyTestDateStarted',
            new_name='genPhyDateStarted',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='genPhyTestRemarks',
            new_name='genPhyRemarks',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='genPhyTestStatus',
            new_name='genPhyStatus',
        ),
    ]
